### PR TITLE
Player kick waiting room

### PR DESCRIPTION
**Pull request by jasminetai**
Oh god. We didn't add kicking players into the host waiting room.

I think this works. Hover over a player's name in the host waiting room to get an X icon. Players receive a kick page upon successful kicking.

### CODE REVIEW

**Comment by 190n** [comment]
The `end` message handling is done already in main. It uses `<MessagePage />` to display a page including the error it got from the server. Here's what it shows if I send the request manually to kick the player:

image

So I don't think you need to change `useKakawGame` or `play/[gameId]/[playerId]` (and I'd rather we didn't change those since I'm making a lot of changes for routing) or add `PlayerKicked.tsx`. Otherwise this works as advertised, thanks for noticing and getting this in on time.

**Comment by jasminetai** [comment]
I saw immediately after noticing the merge conflict. I've changed it to use the MessagePage component.

**Review by 190n — APPROVED** [review]
Thanks. Looks good now.

**Review by rlchoy — APPROVED** [review]
lgtm, thanks for catching that and working on it!

**Pull request merged**
