### PR TITLE
Player answer reveals "Continue", score change, and page titles/icons

### LINKED ISSUE #45: Tabs do not have titles
All of the tabs are given the default title of the url. This does not look great as we finish up. 
Please 
- Give the tabs a title
- (optional) give the tabs an icon

### PR DESCRIPTION
**Pull request by jasminetai**
- added player answer reveal "Continue" button that shows on answer reveals
- added score change that shows on player answer reveals (I think that the score change looks weird when it's static and half in/out of PlayerQuestionBottom, so I think the bouncy animation helps, but tell me if you think it's bad)
- added browser tab titles/icons for all pages
- minor changes to waiting room for host
- extracted 404 for pages without mobile support into NoMobileSupport component, added it to quiz editor page

Mostly some frontend work needed to finish connection page routing stuff.

@190n I know that the leaderboard page should only show "Continue" for the host, but am not sure how you will be using that page along with HostQuestionPage and PlayerQuestionPage. So I kept the "Continue" button there for now, as it probably isn't too hard to make it show/hide on some condition, but if I should change this to make it easier for you, please feel free to say.

### CODE REVIEW

**Review by celdond — DISMISSED** [review]
Oh no you changed the page! Ahhhh-just kidding I want nothing to do with it LOL.

On the animations, it looks fine for me.  Not enough to concern ourselves over for our deadline, anyway.
What I did think was a little wonky was the fact the score change stayed after the answer was revealed, but I understand from a coding perspective why that would be.

On a bit further testing, I noticed the score change is not actually equal to the actual score change.  From testing, I know scoreChange is a field in the websocket, at least from I lasted checked, or is that the job of another branch to route that to this page?

Goodwork though, my approval has not changed.

**Comment by jasminetai** [comment]
@celdond You're right, I had hardcoded the scoreChange here. But I do see that it is already accessible, so I have changed that to take the value from the active kakaw game now.

...And as you seem fine with it, I tampered with the waiting room some more. Those columns bothered me a bit, lol.

**Review by celdond — APPROVED** [review]
Good work!  I don't have any pressing concerns.

Yeah, it bothered me somewhat too, but it was always intended to be a placeholder for a more final design.  There are much better css stylers than I after all.
One note: Player names can be much larger than the amount of text w-52 can contain.

**Comment by jasminetai** [comment]
Noted about w-52, but it's seemingly not a high priority, so I'll leave it.

**Review by 190n — APPROVED** [review]

**Pull request merged**
