### PR TITLE
Navigation from correct answers to leaderboard

### PR DESCRIPTION
**Pull request by 190n**

### CODE REVIEW

**Review by celdond — DISMISSED** [review]
All that remains is hooking up the end endpoint at the last leaderboard, good work.

**Comment by jasminetai** [comment]
It looks like correct answers -> leaderboard has to be reloaded for every question; when the player goes to the leaderboard on question 1, they never see correct answers for the rest of the questions because they stay on leaderboard on all future rounds.

I don't know what the specific issue is yet, but there seems to be some problem with positionChange never being non-zero. Not too important, but maybe you or @rlchoy could look into it?

Otherwise, this is good work.

**Comment by celdond** [comment]
I can confirm Jasmine's comment. Very odd case, but it is consistent.
It correctly handles the points and placements, the players simply cannot see what is wrong and right for any question past the first, to put it in other words.

**Comment by 190n** [comment]
Fixed Jasmine's issue. That was an oversight on my part as the state for whether you are seeing correct answers or the leaderboard needs to be reset between questions; I had done that for the host but not for players.

**Review by celdond — APPROVED** [review]

**Review by jasminetai — APPROVED** [review]
I think jess is going to look at positionChange, so I see no other issues.

**Pull request merged**
