### PR TITLE
End everything

### PR DESCRIPTION
**Pull request by blahajjessie**
Changes in this PR:
- [x] End game when host has been disconnected for too long.
- [x] kick player api
- [x] delete game api

### CODE REVIEW

**Comment by blahajjessie** [comment]
This may fail connection open tests
why?
when the host disconnects, the server waits 5 (well, how ever much is in preferences.ts) before ending the game. 
This causes the tests to time out. 
@celdond this is for you to fix 
until then, change the number in preferences.ts to 1

**Comment by blahajjessie** [comment]
also documentation is changed from #51 so delete game gives a response

**Comment by glapa-grossklag** [comment]
mmm yes looks good to me

**Comment by nmarks413** [comment]
lgtm

**Comment by celdond** [comment]
5?  5 seconds?
If so, yeah that is probably just going over the allocated time for tests, and is an incredibly easy fix.

**Review by rlchoy — APPROVED** [review]

**Review by 190n — APPROVED** [review]

**Pull request merged**
