### PR TITLE
Reafactor codebase

### PR DESCRIPTION
**Pull request by blahajjessie**

### CODE REVIEW

**Comment by blahajjessie** [comment]
Documentation may be incorrect, will be fixed in #34

**Review by rlchoy — APPROVED** [review]
lgtm

**Review by jasminetai — APPROVED** [review]
The other reviewers might have better feedback as they have worked on the related files, but this looks good to me at a glance.

**Review by celdond — APPROVED** [review]
Good work getting all the tests to pass.
I have nothing to add.

**Pull request merged**
